export const lang = 
{
  save: "Save",
  continue: "Continue",
  share: "Share",
  loading: "Loading",
  month: "Month",
  print: "Print",
  listing: "Listing",
  listings: "Listings",
  bedroom: "bedroom",
  bedrooms: "bedrooms",
  bathroom: "bathroom",
  bathrooms: "bathrooms",
  wifi: "Wifi",
  smoking: "Smoking",
  noSmoking: "No Smoking",
  showAllPhotos: "Show all photos",
  space: " ",
  amenities : "Amenities",
  reviews: "Reviews",
  listingAgent: "Listing Agent",
  seeAgentProfile: "See Agent Profile",
  location: "Location",
  checkoutThisListing: "Checkout this Listing!",
  listingDescription :"Listing Description",
  showOriginal: "Show original",
  someInfoAutomaticallyTranslated: "Some info has been automatically translated."
}